/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    TagFilter: typeof import('./src/components/TagFilter.vue')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TaskColumn: typeof import('./src/components/TaskColumn.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
